version: '3.8'
services:
  backend:
    container_name: myapp-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:example@db:3306/myapp
    depends_on:
      - db
      - prisma
  frontend:
    container_name: myapp-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  prisma:
    container_name: myapp-prisma
    build:
      context: ./prisma
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=mysql://root:example@db:3306/myapp
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: myapp-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  mysql-data: